if (NOT DEFINED "MPI_C_COMPILER" OR NOT MPI_C_COMPILER)
  set("MPI_C_COMPILER" "/Users/b80985/.local/share/mamba/envs/liggghts/bin/mpicc" CACHE FILEPATH "Third-party helper setting from ${CMAKE_FIND_PACKAGE_NAME}")
endif ()
if (NOT DEFINED "Python3_EXECUTABLE" OR NOT Python3_EXECUTABLE)
  set("Python3_EXECUTABLE" "/Users/b80985/.local/share/mamba/envs/liggghts/bin/python3.9" CACHE FILEPATH "Third-party helper setting from ${CMAKE_FIND_PACKAGE_NAME}")
endif ()
if (NOT DEFINED "Python3_INCLUDE_DIR" OR NOT Python3_INCLUDE_DIR)
  set("Python3_INCLUDE_DIR" "/Users/b80985/.local/share/mamba/envs/liggghts/include/python3.9" CACHE FILEPATH "Third-party helper setting from ${CMAKE_FIND_PACKAGE_NAME}")
endif ()
if (NOT DEFINED "Python3_LIBRARY" OR NOT Python3_LIBRARY)
  set("Python3_LIBRARY" "/Users/b80985/.local/share/mamba/envs/liggghts/lib/libpython3.9.dylib" CACHE FILEPATH "Third-party helper setting from ${CMAKE_FIND_PACKAGE_NAME}")
endif ()
